name: Deploy documentation

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup DocFX
        run: dotnet tool install -g docfx --version 2.75.3

      - name: Build DNet docs
        run: docfx docs/docfx.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: static-docs
          path: docs/_site
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: static-docs
          path: output/

      #- name: Add CNAME
      #  run: echo "${{ vars.DOCS_DOMAIN }}" > output/CNAME

      - name: Push to the Docs Repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DOCS_DEPLOY_KEY }}
        with:
          source-directory: 'output'
          destination-github-username: 'MartenM'
          destination-repository-name: 'PixelPilotDocs'
          user-email: pixelpilot@martenm.nl
          target-branch: main
          target-directory: docs
